#! /bin/sh
### BEGIN INIT INFO
# Provides:          app-server
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: App Server Init Script
# Description:       Starts and Stops Cherokee Admin and App Server
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Admin <admin@vyperlogix.com>
#
# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="App Server"
NAME=app-server
DAEMON=/root/bin/$NAME
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

#
# Function that starts the daemon/service
#
do_start()
{
	exec /root/app-server/start-app-server.sh
}

#
# Function that stops the daemon/service
#
do_stop()
{
	exec /root/app-server/stop-app-server.sh
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	return 0
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop}" >&2
	echo "Usage: $SCRIPTNAME {start|stop}" >&2
	exit 3
	;;
esac

:
